# Generated by Django 6.0.5 on 2026-05-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('climate', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('mild', 'Mild'), ('cold', 'Cold')], max_length=20)),
                ('meeting_type', models.CharField(choices=[('client', 'Client Meetings'), ('conference', 'Conference / Event'), ('internal', 'Internal Team'), ('mixed', 'Mixed')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any extra context (e.g. black tie dinner, outdoor site visit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
